System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "babel",
  babelOptions: {
    "optional": [
      "runtime",
      "optimisation.modules.system"
    ]
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "build.js": [
      "app/main.js",
      "app/api.js",
      "app/search.js",
      "npm:react@15.3.1.js",
      "npm:react@15.3.1/react.js",
      "npm:react@15.3.1/lib/React.js",
      "github:jspm/nodelibs-process@0.1.2.js",
      "github:jspm/nodelibs-process@0.1.2/index.js",
      "npm:process@0.11.8.js",
      "npm:process@0.11.8/browser.js",
      "npm:react@15.3.1/lib/ReactElementValidator.js",
      "npm:fbjs@0.8.4/lib/warning.js",
      "npm:fbjs@0.8.4/lib/emptyFunction.js",
      "npm:react@15.3.1/lib/getIteratorFn.js",
      "npm:react@15.3.1/lib/canDefineProperty.js",
      "npm:react@15.3.1/lib/checkReactTypeSpec.js",
      "npm:react@15.3.1/lib/ReactComponentTreeHook.js",
      "npm:fbjs@0.8.4/lib/invariant.js",
      "npm:react@15.3.1/lib/ReactCurrentOwner.js",
      "npm:react@15.3.1/lib/reactProdInvariant.js",
      "npm:react@15.3.1/lib/ReactPropTypesSecret.js",
      "npm:react@15.3.1/lib/ReactPropTypeLocationNames.js",
      "npm:react@15.3.1/lib/ReactPropTypeLocations.js",
      "npm:fbjs@0.8.4/lib/keyMirror.js",
      "npm:react@15.3.1/lib/ReactElement.js",
      "npm:object-assign@4.1.0.js",
      "npm:object-assign@4.1.0/index.js",
      "npm:react@15.3.1/lib/onlyChild.js",
      "npm:react@15.3.1/lib/ReactVersion.js",
      "npm:react@15.3.1/lib/ReactPropTypes.js",
      "npm:react@15.3.1/lib/ReactDOMFactories.js",
      "npm:react@15.3.1/lib/ReactClass.js",
      "npm:fbjs@0.8.4/lib/keyOf.js",
      "npm:fbjs@0.8.4/lib/emptyObject.js",
      "npm:react@15.3.1/lib/ReactNoopUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactComponent.js",
      "npm:react@15.3.1/lib/ReactPureComponent.js",
      "npm:react@15.3.1/lib/ReactChildren.js",
      "npm:react@15.3.1/lib/traverseAllChildren.js",
      "npm:react@15.3.1/lib/KeyEscapeUtils.js",
      "npm:react@15.3.1/lib/PooledClass.js",
      "npm:react-bootstrap@0.30.3.js",
      "npm:react-bootstrap@0.30.3/lib/index.js",
      "npm:react-bootstrap@0.30.3/lib/utils/index.js",
      "npm:react-bootstrap@0.30.3/lib/utils/ValidComponentChildren.js",
      "npm:react-bootstrap@0.30.3/lib/utils/createChainedFunction.js",
      "npm:react-bootstrap@0.30.3/lib/utils/bootstrapUtils.js",
      "npm:react-bootstrap@0.30.3/lib/utils/StyleConfig.js",
      "npm:invariant@2.2.1.js",
      "npm:invariant@2.2.1/browser.js",
      "npm:babel-runtime@6.11.6/helpers/extends.js",
      "npm:babel-runtime@6.11.6/core-js/object/assign.js",
      "npm:core-js@2.4.1/library/fn/object/assign.js",
      "npm:core-js@2.4.1/library/modules/_core.js",
      "npm:core-js@2.4.1/library/modules/es6.object.assign.js",
      "npm:core-js@2.4.1/library/modules/_object-assign.js",
      "npm:core-js@2.4.1/library/modules/_fails.js",
      "npm:core-js@2.4.1/library/modules/_iobject.js",
      "npm:core-js@2.4.1/library/modules/_cof.js",
      "npm:core-js@2.4.1/library/modules/_to-object.js",
      "npm:core-js@2.4.1/library/modules/_defined.js",
      "npm:core-js@2.4.1/library/modules/_object-pie.js",
      "npm:core-js@2.4.1/library/modules/_object-gops.js",
      "npm:core-js@2.4.1/library/modules/_object-keys.js",
      "npm:core-js@2.4.1/library/modules/_enum-bug-keys.js",
      "npm:core-js@2.4.1/library/modules/_object-keys-internal.js",
      "npm:core-js@2.4.1/library/modules/_shared-key.js",
      "npm:core-js@2.4.1/library/modules/_uid.js",
      "npm:core-js@2.4.1/library/modules/_shared.js",
      "npm:core-js@2.4.1/library/modules/_global.js",
      "npm:core-js@2.4.1/library/modules/_array-includes.js",
      "npm:core-js@2.4.1/library/modules/_to-index.js",
      "npm:core-js@2.4.1/library/modules/_to-integer.js",
      "npm:core-js@2.4.1/library/modules/_to-length.js",
      "npm:core-js@2.4.1/library/modules/_to-iobject.js",
      "npm:core-js@2.4.1/library/modules/_has.js",
      "npm:core-js@2.4.1/library/modules/_export.js",
      "npm:core-js@2.4.1/library/modules/_hide.js",
      "npm:core-js@2.4.1/library/modules/_descriptors.js",
      "npm:core-js@2.4.1/library/modules/_property-desc.js",
      "npm:core-js@2.4.1/library/modules/_object-dp.js",
      "npm:core-js@2.4.1/library/modules/_to-primitive.js",
      "npm:core-js@2.4.1/library/modules/_is-object.js",
      "npm:core-js@2.4.1/library/modules/_ie8-dom-define.js",
      "npm:core-js@2.4.1/library/modules/_dom-create.js",
      "npm:core-js@2.4.1/library/modules/_an-object.js",
      "npm:core-js@2.4.1/library/modules/_ctx.js",
      "npm:core-js@2.4.1/library/modules/_a-function.js",
      "npm:babel-runtime@6.11.6/core-js/object/entries.js",
      "npm:core-js@2.4.1/library/fn/object/entries.js",
      "npm:core-js@2.4.1/library/modules/es7.object.entries.js",
      "npm:core-js@2.4.1/library/modules/_object-to-array.js",
      "npm:react-bootstrap@0.30.3/lib/Well.js",
      "npm:classnames@2.2.5.js",
      "npm:classnames@2.2.5/index.js",
      "npm:babel-runtime@6.11.6/helpers/inherits.js",
      "npm:babel-runtime@6.11.6/helpers/typeof.js",
      "npm:babel-runtime@6.11.6/core-js/symbol.js",
      "npm:core-js@2.4.1/library/fn/symbol.js",
      "npm:core-js@2.4.1/library/fn/symbol/index.js",
      "npm:core-js@2.4.1/library/modules/es7.symbol.observable.js",
      "npm:core-js@2.4.1/library/modules/_wks-define.js",
      "npm:core-js@2.4.1/library/modules/_wks-ext.js",
      "npm:core-js@2.4.1/library/modules/_wks.js",
      "npm:core-js@2.4.1/library/modules/_library.js",
      "npm:core-js@2.4.1/library/modules/es7.symbol.async-iterator.js",
      "npm:core-js@2.4.1/library/modules/es6.object.to-string.js",
      "npm:core-js@2.4.1/library/modules/es6.symbol.js",
      "npm:core-js@2.4.1/library/modules/_object-gopn.js",
      "npm:core-js@2.4.1/library/modules/_object-gopd.js",
      "npm:core-js@2.4.1/library/modules/_object-gopn-ext.js",
      "npm:core-js@2.4.1/library/modules/_object-create.js",
      "npm:core-js@2.4.1/library/modules/_html.js",
      "npm:core-js@2.4.1/library/modules/_object-dps.js",
      "npm:core-js@2.4.1/library/modules/_is-array.js",
      "npm:core-js@2.4.1/library/modules/_enum-keys.js",
      "npm:core-js@2.4.1/library/modules/_keyof.js",
      "npm:core-js@2.4.1/library/modules/_set-to-string-tag.js",
      "npm:core-js@2.4.1/library/modules/_meta.js",
      "npm:core-js@2.4.1/library/modules/_redefine.js",
      "npm:babel-runtime@6.11.6/core-js/symbol/iterator.js",
      "npm:core-js@2.4.1/library/fn/symbol/iterator.js",
      "npm:core-js@2.4.1/library/modules/web.dom.iterable.js",
      "npm:core-js@2.4.1/library/modules/_iterators.js",
      "npm:core-js@2.4.1/library/modules/es6.array.iterator.js",
      "npm:core-js@2.4.1/library/modules/_iter-define.js",
      "npm:core-js@2.4.1/library/modules/_object-gpo.js",
      "npm:core-js@2.4.1/library/modules/_iter-create.js",
      "npm:core-js@2.4.1/library/modules/_iter-step.js",
      "npm:core-js@2.4.1/library/modules/_add-to-unscopables.js",
      "npm:core-js@2.4.1/library/modules/es6.string.iterator.js",
      "npm:core-js@2.4.1/library/modules/_string-at.js",
      "npm:babel-runtime@6.11.6/core-js/object/create.js",
      "npm:core-js@2.4.1/library/fn/object/create.js",
      "npm:core-js@2.4.1/library/modules/es6.object.create.js",
      "npm:babel-runtime@6.11.6/core-js/object/set-prototype-of.js",
      "npm:core-js@2.4.1/library/fn/object/set-prototype-of.js",
      "npm:core-js@2.4.1/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@2.4.1/library/modules/_set-proto.js",
      "npm:babel-runtime@6.11.6/helpers/possibleConstructorReturn.js",
      "npm:babel-runtime@6.11.6/helpers/classCallCheck.js",
      "npm:babel-runtime@6.11.6/helpers/objectWithoutProperties.js",
      "npm:react-bootstrap@0.30.3/lib/Tooltip.js",
      "npm:react-prop-types@0.4.0/lib/isRequiredForA11y.js",
      "npm:react-bootstrap@0.30.3/lib/Thumbnail.js",
      "npm:react-bootstrap@0.30.3/lib/SafeAnchor.js",
      "npm:react-prop-types@0.4.0/lib/elementType.js",
      "npm:react-prop-types@0.4.0/lib/utils/createChainableTypeChecker.js",
      "npm:react-bootstrap@0.30.3/lib/Tabs.js",
      "npm:react-bootstrap@0.30.3/lib/TabContent.js",
      "npm:react-bootstrap@0.30.3/lib/TabContainer.js",
      "npm:uncontrollable@4.0.3.js",
      "npm:uncontrollable@4.0.3/index.js",
      "npm:uncontrollable@4.0.3/createUncontrollable.js",
      "npm:uncontrollable@4.0.3/utils.js",
      "npm:react-bootstrap@0.30.3/lib/NavItem.js",
      "npm:react-bootstrap@0.30.3/lib/Nav.js",
      "npm:warning@3.0.0.js",
      "npm:warning@3.0.0/browser.js",
      "npm:react-prop-types@0.4.0/lib/all.js",
      "npm:react-dom@15.3.1.js",
      "npm:react-dom@15.3.1/index.js",
      "npm:react@15.3.1/lib/ReactDOM.js",
      "npm:react@15.3.1/lib/ReactDOMNullInputValuePropHook.js",
      "npm:react@15.3.1/lib/ReactDOMUnknownPropertyHook.js",
      "npm:react@15.3.1/lib/EventPluginRegistry.js",
      "npm:react@15.3.1/lib/DOMProperty.js",
      "npm:react@15.3.1/lib/ReactInstrumentation.js",
      "npm:react@15.3.1/lib/ReactDebugTool.js",
      "npm:fbjs@0.8.4/lib/performanceNow.js",
      "npm:fbjs@0.8.4/lib/performance.js",
      "npm:fbjs@0.8.4/lib/ExecutionEnvironment.js",
      "npm:react@15.3.1/lib/ReactChildrenMutationWarningHook.js",
      "npm:react@15.3.1/lib/ReactHostOperationHistoryHook.js",
      "npm:react@15.3.1/lib/ReactInvalidSetStateWarningHook.js",
      "npm:react@15.3.1/lib/renderSubtreeIntoContainer.js",
      "npm:react@15.3.1/lib/ReactMount.js",
      "npm:react@15.3.1/lib/shouldUpdateReactComponent.js",
      "npm:react@15.3.1/lib/setInnerHTML.js",
      "npm:react@15.3.1/lib/createMicrosoftUnsafeLocalFunction.js",
      "npm:react@15.3.1/lib/DOMNamespaces.js",
      "npm:react@15.3.1/lib/instantiateReactComponent.js",
      "npm:react@15.3.1/lib/ReactHostComponent.js",
      "npm:react@15.3.1/lib/ReactEmptyComponent.js",
      "npm:react@15.3.1/lib/ReactCompositeComponent.js",
      "npm:fbjs@0.8.4/lib/shallowEqual.js",
      "npm:react@15.3.1/lib/ReactReconciler.js",
      "npm:react@15.3.1/lib/ReactRef.js",
      "npm:react@15.3.1/lib/ReactOwner.js",
      "npm:react@15.3.1/lib/ReactNodeTypes.js",
      "npm:react@15.3.1/lib/ReactInstanceMap.js",
      "npm:react@15.3.1/lib/ReactErrorUtils.js",
      "npm:react@15.3.1/lib/ReactComponentEnvironment.js",
      "npm:react@15.3.1/lib/ReactUpdates.js",
      "npm:react@15.3.1/lib/Transaction.js",
      "npm:react@15.3.1/lib/ReactFeatureFlags.js",
      "npm:react@15.3.1/lib/CallbackQueue.js",
      "npm:react@15.3.1/lib/ReactUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactMarkupChecksum.js",
      "npm:react@15.3.1/lib/adler32.js",
      "npm:react@15.3.1/lib/ReactDOMFeatureFlags.js",
      "npm:react@15.3.1/lib/ReactDOMContainerInfo.js",
      "npm:react@15.3.1/lib/validateDOMNesting.js",
      "npm:react@15.3.1/lib/ReactDOMComponentTree.js",
      "npm:react@15.3.1/lib/ReactDOMComponentFlags.js",
      "npm:react@15.3.1/lib/ReactBrowserEventEmitter.js",
      "npm:react@15.3.1/lib/isEventSupported.js",
      "npm:react@15.3.1/lib/getVendorPrefixedEventName.js",
      "npm:react@15.3.1/lib/ViewportMetrics.js",
      "npm:react@15.3.1/lib/ReactEventEmitterMixin.js",
      "npm:react@15.3.1/lib/EventPluginHub.js",
      "npm:react@15.3.1/lib/forEachAccumulated.js",
      "npm:react@15.3.1/lib/accumulateInto.js",
      "npm:react@15.3.1/lib/EventPluginUtils.js",
      "npm:react@15.3.1/lib/EventConstants.js",
      "npm:react@15.3.1/lib/DOMLazyTree.js",
      "npm:react@15.3.1/lib/setTextContent.js",
      "npm:react@15.3.1/lib/escapeTextContentForBrowser.js",
      "npm:react@15.3.1/lib/getHostComponentFromComposite.js",
      "npm:react@15.3.1/lib/findDOMNode.js",
      "npm:react@15.3.1/lib/ReactDefaultInjection.js",
      "npm:react@15.3.1/lib/SimpleEventPlugin.js",
      "npm:react@15.3.1/lib/getEventCharCode.js",
      "npm:react@15.3.1/lib/SyntheticWheelEvent.js",
      "npm:react@15.3.1/lib/SyntheticMouseEvent.js",
      "npm:react@15.3.1/lib/getEventModifierState.js",
      "npm:react@15.3.1/lib/SyntheticUIEvent.js",
      "npm:react@15.3.1/lib/getEventTarget.js",
      "npm:react@15.3.1/lib/SyntheticEvent.js",
      "npm:react@15.3.1/lib/SyntheticTransitionEvent.js",
      "npm:react@15.3.1/lib/SyntheticTouchEvent.js",
      "npm:react@15.3.1/lib/SyntheticDragEvent.js",
      "npm:react@15.3.1/lib/SyntheticKeyboardEvent.js",
      "npm:react@15.3.1/lib/getEventKey.js",
      "npm:react@15.3.1/lib/SyntheticFocusEvent.js",
      "npm:react@15.3.1/lib/SyntheticClipboardEvent.js",
      "npm:react@15.3.1/lib/SyntheticAnimationEvent.js",
      "npm:react@15.3.1/lib/EventPropagators.js",
      "npm:fbjs@0.8.4/lib/EventListener.js",
      "npm:react@15.3.1/lib/SelectEventPlugin.js",
      "npm:react@15.3.1/lib/isTextInputElement.js",
      "npm:fbjs@0.8.4/lib/getActiveElement.js",
      "npm:react@15.3.1/lib/ReactInputSelection.js",
      "npm:fbjs@0.8.4/lib/focusNode.js",
      "npm:fbjs@0.8.4/lib/containsNode.js",
      "npm:fbjs@0.8.4/lib/isTextNode.js",
      "npm:fbjs@0.8.4/lib/isNode.js",
      "npm:react@15.3.1/lib/ReactDOMSelection.js",
      "npm:react@15.3.1/lib/getTextContentAccessor.js",
      "npm:react@15.3.1/lib/getNodeForCharacterOffset.js",
      "npm:react@15.3.1/lib/SVGDOMPropertyConfig.js",
      "npm:react@15.3.1/lib/ReactReconcileTransaction.js",
      "npm:react@15.3.1/lib/ReactInjection.js",
      "npm:react@15.3.1/lib/ReactEventListener.js",
      "npm:fbjs@0.8.4/lib/getUnboundedScrollPosition.js",
      "npm:react@15.3.1/lib/ReactDefaultBatchingStrategy.js",
      "npm:react@15.3.1/lib/ReactDOMTextComponent.js",
      "npm:react@15.3.1/lib/DOMChildrenOperations.js",
      "npm:react@15.3.1/lib/ReactMultiChildUpdateTypes.js",
      "npm:react@15.3.1/lib/Danger.js",
      "npm:fbjs@0.8.4/lib/createNodesFromMarkup.js",
      "npm:fbjs@0.8.4/lib/getMarkupWrap.js",
      "npm:fbjs@0.8.4/lib/createArrayFromMixed.js",
      "npm:react@15.3.1/lib/ReactDOMTreeTraversal.js",
      "npm:react@15.3.1/lib/ReactDOMEmptyComponent.js",
      "npm:react@15.3.1/lib/ReactDOMComponent.js",
      "npm:react@15.3.1/lib/ReactServerRenderingTransaction.js",
      "npm:react@15.3.1/lib/ReactServerUpdateQueue.js",
      "npm:react@15.3.1/lib/ReactMultiChild.js",
      "npm:react@15.3.1/lib/flattenChildren.js",
      "npm:react@15.3.1/lib/ReactChildReconciler.js",
      "npm:react@15.3.1/lib/ReactDOMTextarea.js",
      "npm:react@15.3.1/lib/LinkedValueUtils.js",
      "npm:react@15.3.1/lib/DisabledInputUtils.js",
      "npm:react@15.3.1/lib/ReactDOMSelect.js",
      "npm:react@15.3.1/lib/ReactDOMOption.js",
      "npm:react@15.3.1/lib/ReactDOMInput.js",
      "npm:react@15.3.1/lib/DOMPropertyOperations.js",
      "npm:react@15.3.1/lib/quoteAttributeValueForBrowser.js",
      "npm:react@15.3.1/lib/ReactDOMButton.js",
      "npm:react@15.3.1/lib/CSSPropertyOperations.js",
      "npm:fbjs@0.8.4/lib/memoizeStringOnly.js",
      "npm:fbjs@0.8.4/lib/hyphenateStyleName.js",
      "npm:fbjs@0.8.4/lib/hyphenate.js",
      "npm:react@15.3.1/lib/dangerousStyleValue.js",
      "npm:react@15.3.1/lib/CSSProperty.js",
      "npm:fbjs@0.8.4/lib/camelizeStyleName.js",
      "npm:fbjs@0.8.4/lib/camelize.js",
      "npm:react@15.3.1/lib/AutoFocusUtils.js",
      "npm:react@15.3.1/lib/ReactComponentBrowserEnvironment.js",
      "npm:react@15.3.1/lib/ReactDOMIDOperations.js",
      "npm:react@15.3.1/lib/HTMLDOMPropertyConfig.js",
      "npm:react@15.3.1/lib/EnterLeaveEventPlugin.js",
      "npm:react@15.3.1/lib/DefaultEventPluginOrder.js",
      "npm:react@15.3.1/lib/ChangeEventPlugin.js",
      "npm:react@15.3.1/lib/BeforeInputEventPlugin.js",
      "npm:react@15.3.1/lib/SyntheticInputEvent.js",
      "npm:react@15.3.1/lib/SyntheticCompositionEvent.js",
      "npm:react@15.3.1/lib/FallbackCompositionState.js",
      "npm:keycode@2.1.4.js",
      "npm:keycode@2.1.4/index.js",
      "npm:react-bootstrap@0.30.3/lib/TabPane.js",
      "npm:react-bootstrap@0.30.3/lib/Fade.js",
      "npm:react-overlays@0.6.6/lib/Transition.js",
      "npm:dom-helpers@2.4.0/events/on.js",
      "npm:dom-helpers@2.4.0/util/inDOM.js",
      "npm:dom-helpers@2.4.0/transition/properties.js",
      "npm:react-bootstrap@0.30.3/lib/Table.js",
      "npm:react-bootstrap@0.30.3/lib/Tab.js",
      "npm:react-bootstrap@0.30.3/lib/SplitButton.js",
      "npm:react-bootstrap@0.30.3/lib/utils/splitComponentProps.js",
      "npm:react-bootstrap@0.30.3/lib/SplitToggle.js",
      "npm:react-bootstrap@0.30.3/lib/DropdownToggle.js",
      "npm:react-bootstrap@0.30.3/lib/Button.js",
      "npm:babel-runtime@6.11.6/core-js/object/values.js",
      "npm:core-js@2.4.1/library/fn/object/values.js",
      "npm:core-js@2.4.1/library/modules/es7.object.values.js",
      "npm:react-bootstrap@0.30.3/lib/Dropdown.js",
      "npm:react-bootstrap@0.30.3/lib/utils/PropTypes.js",
      "npm:react-bootstrap@0.30.3/lib/DropdownMenu.js",
      "npm:react-overlays@0.6.6/lib/RootCloseWrapper.js",
      "npm:react-overlays@0.6.6/lib/utils/ownerDocument.js",
      "npm:dom-helpers@2.4.0/ownerDocument.js",
      "npm:react-overlays@0.6.6/lib/utils/createChainedFunction.js",
      "npm:react-overlays@0.6.6/lib/utils/addEventListener.js",
      "npm:dom-helpers@2.4.0/events/off.js",
      "npm:babel-runtime@6.11.6/core-js/array/from.js",
      "npm:core-js@2.4.1/library/fn/array/from.js",
      "npm:core-js@2.4.1/library/modules/es6.array.from.js",
      "npm:core-js@2.4.1/library/modules/_iter-detect.js",
      "npm:core-js@2.4.1/library/modules/core.get-iterator-method.js",
      "npm:core-js@2.4.1/library/modules/_classof.js",
      "npm:core-js@2.4.1/library/modules/_create-property.js",
      "npm:core-js@2.4.1/library/modules/_is-array-iter.js",
      "npm:core-js@2.4.1/library/modules/_iter-call.js",
      "npm:react-bootstrap@0.30.3/lib/ButtonGroup.js",
      "npm:dom-helpers@2.4.0/query/contains.js",
      "npm:dom-helpers@2.4.0/activeElement.js",
      "npm:dom-helpers@2.4.0/util/babelHelpers.js",
      "npm:react-bootstrap@0.30.3/lib/Row.js",
      "npm:react-bootstrap@0.30.3/lib/ResponsiveEmbed.js",
      "npm:react-bootstrap@0.30.3/lib/Radio.js",
      "npm:react-bootstrap@0.30.3/lib/ProgressBar.js",
      "npm:react-bootstrap@0.30.3/lib/Popover.js",
      "npm:react-bootstrap@0.30.3/lib/PanelGroup.js",
      "npm:react-bootstrap@0.30.3/lib/Panel.js",
      "npm:react-bootstrap@0.30.3/lib/Collapse.js",
      "npm:react-bootstrap@0.30.3/lib/utils/capitalize.js",
      "npm:dom-helpers@2.4.0/style.js",
      "npm:dom-helpers@2.4.0/style/index.js",
      "npm:dom-helpers@2.4.0/style/removeStyle.js",
      "npm:dom-helpers@2.4.0/style/getComputedStyle.js",
      "npm:dom-helpers@2.4.0/util/camelizeStyle.js",
      "npm:dom-helpers@2.4.0/util/camelize.js",
      "npm:dom-helpers@2.4.0/util/hyphenateStyle.js",
      "npm:dom-helpers@2.4.0/util/hyphenate.js",
      "npm:react-bootstrap@0.30.3/lib/Pagination.js",
      "npm:react-bootstrap@0.30.3/lib/PaginationButton.js",
      "npm:react-bootstrap@0.30.3/lib/Pager.js",
      "npm:react-bootstrap@0.30.3/lib/PagerItem.js",
      "npm:react-bootstrap@0.30.3/lib/PageItem.js",
      "npm:react-bootstrap@0.30.3/lib/utils/deprecationWarning.js",
      "npm:react-bootstrap@0.30.3/lib/PageHeader.js",
      "npm:react-bootstrap@0.30.3/lib/OverlayTrigger.js",
      "npm:react-bootstrap@0.30.3/lib/Overlay.js",
      "npm:react-overlays@0.6.6/lib/Overlay.js",
      "npm:react-overlays@0.6.6/lib/Position.js",
      "npm:react-overlays@0.6.6/lib/utils/getContainer.js",
      "npm:react-overlays@0.6.6/lib/utils/calculatePosition.js",
      "npm:dom-helpers@2.4.0/query/scrollTop.js",
      "npm:dom-helpers@2.4.0/query/isWindow.js",
      "npm:dom-helpers@2.4.0/query/position.js",
      "npm:dom-helpers@2.4.0/query/scrollLeft.js",
      "npm:dom-helpers@2.4.0/query/offsetParent.js",
      "npm:dom-helpers@2.4.0/query/offset.js",
      "npm:react-prop-types@0.4.0/lib/componentOrElement.js",
      "npm:react-overlays@0.6.6/lib/Portal.js",
      "npm:react-bootstrap@0.30.3/lib/NavDropdown.js",
      "npm:react-bootstrap@0.30.3/lib/NavbarBrand.js",
      "npm:react-bootstrap@0.30.3/lib/Navbar.js",
      "npm:react-bootstrap@0.30.3/lib/NavbarToggle.js",
      "npm:react-bootstrap@0.30.3/lib/NavbarHeader.js",
      "npm:react-bootstrap@0.30.3/lib/NavbarCollapse.js",
      "npm:react-bootstrap@0.30.3/lib/Grid.js",
      "npm:react-bootstrap@0.30.3/lib/ModalTitle.js",
      "npm:react-bootstrap@0.30.3/lib/ModalHeader.js",
      "npm:react-bootstrap@0.30.3/lib/ModalFooter.js",
      "npm:react-bootstrap@0.30.3/lib/ModalBody.js",
      "npm:react-bootstrap@0.30.3/lib/Modal.js",
      "npm:react-bootstrap@0.30.3/lib/ModalDialog.js",
      "npm:react-overlays@0.6.6/lib/utils/isOverflowing.js",
      "npm:react-overlays@0.6.6/lib/Modal.js",
      "npm:react-overlays@0.6.6/lib/utils/addFocusListener.js",
      "npm:react-overlays@0.6.6/lib/ModalManager.js",
      "npm:react-overlays@0.6.6/lib/utils/manageAriaHidden.js",
      "npm:dom-helpers@2.4.0/util/scrollbarSize.js",
      "npm:dom-helpers@2.4.0/class.js",
      "npm:dom-helpers@2.4.0/class/index.js",
      "npm:dom-helpers@2.4.0/class/hasClass.js",
      "npm:dom-helpers@2.4.0/class/removeClass.js",
      "npm:dom-helpers@2.4.0/class/addClass.js",
      "npm:dom-helpers@2.4.0/events.js",
      "npm:dom-helpers@2.4.0/events/index.js",
      "npm:dom-helpers@2.4.0/events/filter.js",
      "npm:dom-helpers@2.4.0/query/querySelectorAll.js",
      "npm:react-bootstrap@0.30.3/lib/MenuItem.js",
      "npm:react-bootstrap@0.30.3/lib/Media.js",
      "npm:react-bootstrap@0.30.3/lib/MediaRight.js",
      "npm:react-bootstrap@0.30.3/lib/MediaListItem.js",
      "npm:react-bootstrap@0.30.3/lib/MediaList.js",
      "npm:react-bootstrap@0.30.3/lib/MediaLeft.js",
      "npm:react-bootstrap@0.30.3/lib/MediaHeading.js",
      "npm:react-bootstrap@0.30.3/lib/MediaBody.js",
      "npm:react-bootstrap@0.30.3/lib/ListGroupItem.js",
      "npm:react-bootstrap@0.30.3/lib/ListGroup.js",
      "npm:react-bootstrap@0.30.3/lib/Label.js",
      "npm:react-bootstrap@0.30.3/lib/Jumbotron.js",
      "npm:react-bootstrap@0.30.3/lib/InputGroup.js",
      "npm:react-bootstrap@0.30.3/lib/InputGroupButton.js",
      "npm:react-bootstrap@0.30.3/lib/InputGroupAddon.js",
      "npm:react-bootstrap@0.30.3/lib/Image.js",
      "npm:react-bootstrap@0.30.3/lib/HelpBlock.js",
      "npm:react-bootstrap@0.30.3/lib/Glyphicon.js",
      "npm:react-bootstrap@0.30.3/lib/FormGroup.js",
      "npm:react-bootstrap@0.30.3/lib/FormControl.js",
      "npm:react-bootstrap@0.30.3/lib/FormControlStatic.js",
      "npm:react-bootstrap@0.30.3/lib/FormControlFeedback.js",
      "npm:react-bootstrap@0.30.3/lib/Form.js",
      "npm:react-bootstrap@0.30.3/lib/DropdownButton.js",
      "npm:react-bootstrap@0.30.3/lib/Col.js",
      "npm:react-bootstrap@0.30.3/lib/ControlLabel.js",
      "npm:react-bootstrap@0.30.3/lib/Clearfix.js",
      "npm:react-bootstrap@0.30.3/lib/Checkbox.js",
      "npm:react-bootstrap@0.30.3/lib/CarouselItem.js",
      "npm:react-bootstrap@0.30.3/lib/utils/TransitionEvents.js",
      "npm:react-bootstrap@0.30.3/lib/Carousel.js",
      "npm:react-bootstrap@0.30.3/lib/CarouselCaption.js",
      "npm:react-bootstrap@0.30.3/lib/ButtonToolbar.js",
      "npm:react-bootstrap@0.30.3/lib/BreadcrumbItem.js",
      "npm:react-bootstrap@0.30.3/lib/Breadcrumb.js",
      "npm:react-bootstrap@0.30.3/lib/Badge.js",
      "npm:react-bootstrap@0.30.3/lib/Alert.js",
      "npm:react-bootstrap@0.30.3/lib/Accordion.js",
      "npm:babel-runtime@5.8.38/helpers/class-call-check.js",
      "npm:babel-runtime@5.8.38/helpers/create-class.js",
      "npm:babel-runtime@5.8.38/core-js/object/define-property.js",
      "npm:core-js@1.2.7/library/fn/object/define-property.js",
      "npm:core-js@1.2.7/library/modules/$.js",
      "npm:babel-runtime@5.8.38/helpers/inherits.js",
      "npm:babel-runtime@5.8.38/core-js/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/fn/object/set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.core.js",
      "npm:core-js@1.2.7/library/modules/es6.object.set-prototype-of.js",
      "npm:core-js@1.2.7/library/modules/$.set-proto.js",
      "npm:core-js@1.2.7/library/modules/$.ctx.js",
      "npm:core-js@1.2.7/library/modules/$.a-function.js",
      "npm:core-js@1.2.7/library/modules/$.an-object.js",
      "npm:core-js@1.2.7/library/modules/$.is-object.js",
      "npm:core-js@1.2.7/library/modules/$.export.js",
      "npm:core-js@1.2.7/library/modules/$.global.js",
      "npm:babel-runtime@5.8.38/core-js/object/create.js",
      "npm:core-js@1.2.7/library/fn/object/create.js",
      "npm:babel-runtime@5.8.38/helpers/get.js",
      "npm:babel-runtime@5.8.38/core-js/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/fn/object/get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/es6.object.get-own-property-descriptor.js",
      "npm:core-js@1.2.7/library/modules/$.object-sap.js",
      "npm:core-js@1.2.7/library/modules/$.fails.js",
      "npm:core-js@1.2.7/library/modules/$.to-iobject.js",
      "npm:core-js@1.2.7/library/modules/$.defined.js",
      "npm:core-js@1.2.7/library/modules/$.iobject.js",
      "npm:core-js@1.2.7/library/modules/$.cof.js",
      "app/display.js",
      "app/main.css!github:systemjs/plugin-css@0.1.27.js",
      "app/assets/styles/bootstrap.min.css!github:systemjs/plugin-css@0.1.27.js"
    ]
  },

  map: {
    "babel": "npm:babel-core@5.8.38",
    "babel-runtime": "npm:babel-runtime@5.8.38",
    "core-js": "npm:core-js@1.2.7",
    "css": "github:systemjs/plugin-css@0.1.27",
    "react": "npm:react@15.3.1",
    "react-bootstrap": "npm:react-bootstrap@0.30.3",
    "react-dom": "npm:react-dom@15.3.1",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.4.1"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.6.0"
    },
    "github:jspm/nodelibs-domain@0.1.0": {
      "domain-browser": "npm:domain-browser@1.1.7"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-http@1.7.1": {
      "Base64": "npm:Base64@0.2.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "github:jspm/nodelibs-https@0.1.0": {
      "https-browserify": "npm:https-browserify@0.0.0"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.8"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-url@0.1.0": {
      "url": "npm:url@0.10.3"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "github:jspm/nodelibs-zlib@0.1.0": {
      "browserify-zlib": "npm:browserify-zlib@0.1.4"
    },
    "npm:asap@2.0.4": {
      "domain": "github:jspm/nodelibs-domain@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:assert@1.4.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "util": "npm:util@0.10.3"
    },
    "npm:babel-runtime@5.8.38": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:babel-runtime@6.11.6": {
      "core-js": "npm:core-js@2.4.1",
      "regenerator-runtime": "npm:regenerator-runtime@0.9.5"
    },
    "npm:browserify-zlib@0.1.4": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "pako": "npm:pako@0.2.9",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "readable-stream": "npm:readable-stream@2.1.5",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:buffer-shims@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:buffer@3.6.0": {
      "base64-js": "npm:base64-js@0.0.8",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "ieee754": "npm:ieee754@1.1.6",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:core-js@1.2.7": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-js@2.4.1": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:core-util-is@1.0.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:domain-browser@1.1.7": {
      "events": "github:jspm/nodelibs-events@0.1.1"
    },
    "npm:encoding@0.1.12": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "iconv-lite": "npm:iconv-lite@0.4.13"
    },
    "npm:fbjs@0.8.4": {
      "core-js": "npm:core-js@1.2.7",
      "immutable": "npm:immutable@3.8.1",
      "isomorphic-fetch": "npm:isomorphic-fetch@2.2.1",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "promise": "npm:promise@7.1.1",
      "ua-parser-js": "npm:ua-parser-js@0.7.10"
    },
    "npm:https-browserify@0.0.0": {
      "http": "github:jspm/nodelibs-http@1.7.1"
    },
    "npm:iconv-lite@0.4.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:invariant@2.2.1": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:isomorphic-fetch@2.2.1": {
      "node-fetch": "npm:node-fetch@1.6.0",
      "whatwg-fetch": "npm:whatwg-fetch@1.0.0"
    },
    "npm:loose-envify@1.2.0": {
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "js-tokens": "npm:js-tokens@1.0.3",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:node-fetch@1.6.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "encoding": "npm:encoding@0.1.12",
      "http": "github:jspm/nodelibs-http@1.7.1",
      "https": "github:jspm/nodelibs-https@0.1.0",
      "is-stream": "npm:is-stream@1.1.0",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "url": "github:jspm/nodelibs-url@0.1.0",
      "util": "github:jspm/nodelibs-util@0.1.0",
      "zlib": "github:jspm/nodelibs-zlib@0.1.0"
    },
    "npm:pako@0.2.9": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process-nextick-args@1.0.7": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:process@0.11.8": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:promise@7.1.1": {
      "asap": "npm:asap@2.0.4",
      "fs": "github:jspm/nodelibs-fs@0.1.2"
    },
    "npm:punycode@1.3.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:react-bootstrap@0.30.3": {
      "babel-runtime": "npm:babel-runtime@6.11.6",
      "classnames": "npm:classnames@2.2.5",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "invariant": "npm:invariant@2.2.1",
      "keycode": "npm:keycode@2.1.4",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1",
      "react-dom": "npm:react-dom@15.3.1",
      "react-overlays": "npm:react-overlays@0.6.6",
      "react-prop-types": "npm:react-prop-types@0.4.0",
      "uncontrollable": "npm:uncontrollable@4.0.3",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react-dom@15.3.1": {
      "react": "npm:react@15.3.1"
    },
    "npm:react-overlays@0.6.6": {
      "classnames": "npm:classnames@2.2.5",
      "dom-helpers": "npm:dom-helpers@2.4.0",
      "react": "npm:react@15.3.1",
      "react-dom": "npm:react-dom@15.3.1",
      "react-prop-types": "npm:react-prop-types@0.4.0",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react-prop-types@0.4.0": {
      "react": "npm:react@15.3.1",
      "warning": "npm:warning@3.0.0"
    },
    "npm:react@15.3.1": {
      "fbjs": "npm:fbjs@0.8.4",
      "loose-envify": "npm:loose-envify@1.2.0",
      "object-assign": "npm:object-assign@4.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.14": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:readable-stream@2.1.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-shims": "npm:buffer-shims@1.0.0",
      "core-util-is": "npm:core-util-is@1.0.2",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@1.0.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "process-nextick-args": "npm:process-nextick-args@1.0.7",
      "string_decoder": "npm:string_decoder@0.10.31",
      "util-deprecate": "npm:util-deprecate@1.0.2"
    },
    "npm:regenerator-runtime@0.9.5": {
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.14"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:ua-parser-js@0.7.10": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.2"
    },
    "npm:uncontrollable@4.0.3": {
      "invariant": "npm:invariant@2.2.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "react": "npm:react@15.3.1"
    },
    "npm:url@0.10.3": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "punycode": "npm:punycode@1.3.2",
      "querystring": "npm:querystring@0.2.0",
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util-deprecate@1.0.2": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:warning@3.0.0": {
      "loose-envify": "npm:loose-envify@1.2.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
